### ISSUE TITLE
dlopen() fails on Windows

### ISSUE THREAD

**Issue by SimonSapin** [Kozea/cairocffi#1]
Reported by @randfb on Reddit:

http://www.reddit.com/r/Python/comments/165bbf/cairocffi_dropin_pycairo_replacement_installs/c7tjwo7
http://www.reddit.com/r/Python/comments/165bbf/cairocffi_dropin_pycairo_replacement_installs/c7tkae4

> I can't install on windows. I had pycairo working fine.
> I can do a:
> 
> ```
> import cairo
> ```
> 
> without errors, but not
> 
> ```
> import cairocffi as cairo
> ```
> 
> 319         path = ctypes.util.find_library(name)
> 320         if path is None:
> --> 321 raise OSError("library not found: %r" % (name,))
> 322 #
> 323 backend = ffi._backend
> 
> OSError: library not found: 'cairo'

It seems that dlopen() fails to find cairo.dll.

@randfb, how did you install pycairo and cairo?

**Comment by sasnfbi1234** [comment]
There is no ffi.dlopen('cairo') and I am still having this issue

**Comment by SimonSapin** [comment]
@sasnfbi1234 Yes, on Windows it’s (probably) `ffi.dlopen('libcairo-2')`. Did you install cairo?
