### ISSUE TITLE
Set version_info/version in install_as_pycairo

### ISSUE THREAD

**Issue by lazka** [Kozea/cairocffi#10]
I'm playing around with matplotlib atm, which uses `version_info` and `version` to check if the installed pycairo is recent enough.

I suggest adding something like this in `install_as_pycairo()`:

```
globals()["version_info"] = (1, 10, 0)
globals()["version"] = "1.10.0"
```

**Comment by anntzer** [comment]
fwiw I'm going to bump mpl's min pycairo version to 1.11.0 and make the check only happen for pycairo, not cairocffi, so this hack may be removed...
