### ISSUE TITLE
Confusing error when cairocffi installed without xcffib support

### ISSUE THREAD

**Issue by willstott101** [Kozea/cairocffi#100]
I installed xcffib AFTER installing cairocffi and got the following error trying to use the XCBSurface:

    AttributeError: cffi library 'libcairo.so.2' has no function, constant or global variable named 'cairo_xcb_surface_create'

which obviously sent me down a rabbit hole of checking for manually installed versions of libcairo.

All I needed to do was re-install cairocffi

Maybe the installation order should be documented, or there's some way you can tell the difference and have a nicer error message.

I may have a look at fleshing out the documentation for drawing to XCB myself soon.

**Comment by tych0** [comment]
I think if we add xcffib unconditionally to install_requires=, this would go away. However, then we'd also have to add it as an unconditional dependency, instead of an extra.

That would make things much easier for our users, if that's ok with the cairocffi folks I can send a patch? As it stands right now, there's not a great way to install cairocffi with a one-liner that always gets the right deps in the right order.

**Comment by liZe** [comment]
I agree, we should improve the documentation and/or the error.

> I think if we add xcffib unconditionally to install_requires=, this would go away. However, then we'd also have to add it as an unconditional dependency, instead of an extra.

That would be a problem because xcffib requires some Xorg-related dependencies, and that's pretty heavy for servers that don't require an X server.

> As it stands right now, there's not a great way to install cairocffi with a one-liner that always gets the right deps in the right order.

Doesn't `pip install cairocffi[xcb]` work?

**Comment by tych0** [comment]
Unfortunately it doesn't. The problem is that since xcffib isn't listed in install_requires, pip feels it can install things in any order. But since cairocffi builds the binding (and thus does the detection about whether xcffib is present) at install time, if pip happens to choose to install cairocffi first (e.g. because it's first alphabetically, but they say here they reserve the right to do things in any order: https://github.com/pypa/pip/issues/3966#issuecomment-247697230 ), then it'll detect that there's no xcffib present. Subsequently pip will install xcffib, so it looks like everything is "ok", but the binding was not built without xcb support, and users get the error above.

They can force reinstall it (maybe they have to clear their cache, etc. etc.), but still, it would be nicer to just not have this problem. It's like we need an extras_install_requires or something, but as near as I can tell pip doesn't support anything like this.

**Comment by liZe** [comment]
> Unfortunately it doesn't.

That's sad. Unfortunately, I don't see any easy solution to fix that. We could at least change the documentation to propose `pip install xcffib cairocffi`.

Maybe the best solution is to have a nice error message when trying to import the missing module, asking the user to reinstall cairocffi (and xcffib before if needed).

**Comment by oleg-alexandrov** [comment]
I am running into this as well. Uninstalling everything and doing 

 pip install xcffib cairocffi

does not help. Quering my cairo lib for similar symbols like this:

strings /home/user/miniconda3/lib/python3.7/site-packages/../../libcairo.so | grep -i xcb

gives only the 

  cairo-xlib-xcb-surface.c 

symbol. My cairo version appears to be libcairo.so.2.11400.12. Doing conda list (I used conda for installation) shows version 1.14.12. Anyhow, this seems to be a pain.

**Comment by oleg-alexandrov** [comment]
Uninstalling them both, yet again, and installing first xcffib and then cairocffi also did not help.

**Comment by oleg-alexandrov** [comment]
Wiping it all and installing cairo 1.16.0 with conda from conda-forge, then doing xcffib first, and then cairocffi later helped. Maybe cairo 1.14.12 is too old, or when I wiped things yet again something got cleaned more thoroughly.

**Comment by liZe** [comment]
> or when I wiped things yet again something got cleaned more thoroughly.

That’s probably what happened.

**Comment by tych0** [comment]
FWIW I think `pip install xcffib cairocffi` isn't enough; pip is still free to re-order things. I think it really has to be in two separate invocations of pip, i.e. `pip install xcffib; pip install cairocffi`.

**Comment by liZe** [comment]
> FWIW I think `pip install xcffib cairocffi` isn't enough; pip is still free to re-order things. I think it really has to be in two separate invocations of pip, i.e. `pip install xcffib; pip install cairocffi`.

:facepalm:

**Comment by oleg-alexandrov** [comment]
I understand that cairocffi  does not want xcffib as a prerequisite. The least one can do then is to clarify the documentation at https://cairocffi.readthedocs.io/en/latest/ to address the case when one needs these packages together. It is probably a frequent use case as on a Linux desktop likely they are both needed.

**Comment by titosbet** [comment]
The pip order of packages did not work for me, on a rapian buster on raspberry 4, despite repeating the process for some 10 times, explicitly installing them one by one in separate commands.

What did work was this:
After installing both libraries, also do a `pip download cairocffi` . 
Then uncompress the download whl of cairocffi (its practically a zip). 
Then edit ffi_build.py in the root of the unzipped cairocffi folder and remove the try: ... except pass clause around these lines:. 
`
from xcffib.ffi_build import ffi as xcb_ffi
ffi.include(xcb_ffi)
ffi.cdef(constants._CAIRO_XCB_HEADERS)
`
In my version (1.2.0) it was on line 31, so I guess it can't be too far in any case. 
One with a little knowledge of python can also use a raise command or print something, just to be sure that it does not fail silently. Even if one can't, don't worry it's an optional step, it may work anyway.

Then run ffi_build.py
After this, xcb.py/ test_xcb.py still fails for trying some import. , but don't worry, we'll use the installed version of cairocffi, not this.
Then copy the contents of folder cairocffi/_generated to the pip-installed cairocffi in a same named _generated folder .
Note that this is another cairocffi folder inside the on created from the unzipping process, which name is also likely to be cairocffi.
The command in my case was: 
` sudo cp -bv cairocffi/_generated/* /usr/local/lib/python3.7/dist-packages/cairocffi/_generated/ `
(-b keeps the backups in case something goes wrong)

This may help, if anyone encounters the exact same problem with mine.

**Comment by mcuee** [comment]
I encountered the issue building qtile with Raspberry Pi 400 running Raspberry Pi OS as well and the steps by titosbet works nicely.

```
sudo pip3 install xcffib
sudo pip3 install cairocffi
pip3 download cairocffi
unzip cairocffi-1.2.0-py3-none-any.whl
cd cairocffi
vim ffi_build.py
python3 ffi_build.py
sudo cp -bv cairocffi/_generated/* /usr/local/lib/python3.7/dist-packages/cairocffi/_generated
sudo pip3 install qtile
```

**Comment by arf20** [comment]
This does not work in Debian 12
