### ISSUE TITLE
set_source_surface from RecordingSurface to PDFSurface with origin translation gives a PNG but empty PDF

### ISSUE THREAD

**Issue by 4doom4** [Kozea/cairocffi#104]
Hi there,

in this example I am drawing some line elements 30px away from the origin in the Y coordinate while moving along he X coordinate. This is drawn on a recording surface because in my real code I don't know the extend before I start. After drawing is done I repeat the drawing on the PDFSurface but since I want my PDF and PNG to end flush with my drawn elements I set the boundaries of the PDFSurface to the height and width of the ink_extents of the RecordingSurface. Next because I was drawing 30px lower with only empty space above I translate my drawing in set_source_surface -30px. Now when writing the PNG all works fine but the PDF is empty. If I extend the height to 100px manually the PDF is drawn correctly with the correct origin. If I start drawing at Y 0px instead of Y 30px it also works. Do I miss anything or is it a bug?

Thanks for your help. Here is a test code:

```
rs = cairo.RecordingSurface(cairo.CONTENT_COLOR_ALPHA, None)
ctxRS = cairo.Context(rs)

items = ([0], [28, 29], [39], [42], [64], [67], [70, 71, 72], [76, 77], [79, 80], [86], [90], [104, 105],
         [131], [134, 135, 136, 137, 138, 139], [145, 146, 147], [150, 151], [156], [174], [188], [191],
         [199, 200], [203], [212], [216], [229, 230], [240, 241, 242, 243], [262])

for item in items:
    initialPosition = item[0]
    numberOfItems = len(item)

    offset = initialPosition * 10
    lineLength = 10 * numberOfItems

    ctxRS.set_source_rgba(1.0, 0.0, 0.0, 1.0)
    ctxRS.set_line_width(0)
    ctxRS.move_to(offset, 30)
    ctxRS.line_to(offset, 40)
    ctxRS.line_to(offset + lineLength, 40)
    ctxRS.line_to(offset + lineLength, 30)
    ctxRS.close_path()
    ctxRS.stroke_preserve()
    ctxRS.set_source_rgba(1.0, 0.0, 0.0, 1.0)
    ctxRS.fill()

x, y, width, height = rs.ink_extents()
ps = cairo.PDFSurface("cairoTest.pdf", width, height)
ctxPS = cairo.Context(ps)
ctxPS.set_source_surface(rs, -x, -y)
ctxPS.paint()
ps.write_to_png("cairoTest.png")
ps.finish()
```

**Comment by liZe** [comment]
There are known bugs in Cairo with RecordingSurfaces and negative coordinates, there's a [thread on the mailing list about that](https://lists.cairographics.org/archives/cairo/2017-July/028236.html). It's probably a bug in Cairo and not in CairoCFFI.

Could you try a recent development version of Cairo and see if it fixes your problem?

**Comment by 4doom4** [comment]
Let me check it out and I will get back to you.

**Comment by 4doom4** [comment]
I just compiled cairo snapshot 1.15.6 and it works. Now the negative RecordingSurface is no problem anymore. So indeed it is a cairo bug not the python project here. Sorry for that. I was just wondering where do I specify in CairoCFFI the location of my local cairo installation so that I can run the snapshot and stable version side by side?

**Comment by 4doom4** [comment]
I just compiled cairo snapshot 1.15.6 and it works. Now the negative RecordingSurface is no problem anymore. So indeed it is a cairo bug not the python project here. Sorry for that. I was just wondering where do I specify in CairoCFFI the location of my local cairo installation so that I can run the snapshot and stable version side by side?

**Comment by liZe** [comment]
CairoCFFI uses [`find_library`](https://docs.python.org/3/library/ctypes.html?highlight=ctypes.util#finding-shared-libraries) to find the library. The way it works depends on your system, you'll easily find somewhere on the Internet how to set the location. Good luck!
