### ISSUE TITLE
write_to_png does not work on macOS and on Linux hardened systems

### ISSUE THREAD

**Issue by codingcatgirl** [Kozea/cairocffi#106]
Migrating cairocffi so it uses the faster cffi API mode and [new-style callbacks](http://cffi.readthedocs.io/en/latest/using.html?highlight=callback#extern-python-new-style-callbacks) would solve this problem. See also #105.

**Comment by liZe** [comment]
The fix in d7bb680 is not perfect, but it should at least make `write_to_png` work on macOS and hardened systems.

@codingcatgirl If you’re interested in testing this fix, let me know! I’ll use this workaround everywhere it’s possible.

**Comment by codingcatgirl** [comment]
I'm currently unable to test this, maybe @evilscientress can?

**Comment by evilscientress** [comment]
Sadly not. Back then grsecurity hardened kernels where still a thing. I don't have a system with kernel anymore with hardening of that kind. IIRC the problem was memory that was RWX mapped. grsec didn't allow such memory allocations.
