### ISSUE TITLE
'--record {plist}' writes an incomplete file list

### ISSUE THREAD

**Issue by yurivict** [Kozea/cairocffi#108]
'--record {plist}' is supposed to write the correct list.

The following files are missing in version 0.8.0:
```
%%PYTHON_SITELIBDIR%%/cairocffi/_ffi.py
%%PYTHON_SITELIBDIR%%/cairocffi/_ffi.pyc
%%PYTHON_SITELIBDIR%%/cairocffi/_ffi.%%PYTHON_PYOEXTENSION%%
%%PYTHON_SITELIBDIR%%/cairocffi/_ffi_pixbuf.py
%%PYTHON_SITELIBDIR%%/cairocffi/_ffi_pixbuf.pyc
%%PYTHON_SITELIBDIR%%/cairocffi/_ffi_pixbuf.%%PYTHON_PYOEXTENSION%%
```

**Comment by liZe** [comment]
What's '--record {plist}'?

**Comment by yurivict** [comment]
This is a feature of python distutils that records the install file list.

**Comment by liZe** [comment]
Well, it's because some cffi modules are generated at install time and are not included in the list of distributed files. I don't know if the cffi module provides anything to fix that.

**Comment by liZe** [comment]
This bug is now fixed.
