### ISSUE TITLE
Is there a cairocffi function like cv2.copyMakeBorder?

### ISSUE THREAD

**Issue by sheirving** [Kozea/cairocffi#118]
A Imagesurface is created, I want to pad this surface like opencv function(cv2.copyMakeBorder), Is there a function like this? Thankyou.

**Comment by liZe** [comment]
I think that your question is more a question about Cairo features, not CairoCFFI (that's just a Python wrapper around Cairo functions). Unfortunately, I don't think that such a feature exists in Cairo, there's no real layout.

You'll probably find more information in [Cairo's API](https://cairographics.org/manual/index.html).
