### ISSUE TITLE
Version 1.0 broken when setup.py installed

### ISSUE THREAD

**Issue by flacjacket** [Kozea/cairocffi#120]
In qtile, we use cairocffi, and the tests have started to fail with
```
libqtile/drawer.py:33: in <module>
    import cairocffi
.tox/py36/lib/python3.6/site-packages/cairocffi/__init__.py:17: in <module>
    from ._generated.ffi import ffi
E   ModuleNotFoundError: No module named 'cairocffi._generated.ffi'
```
The `_generated` folder that is built does not have a `__init__.py` generated in it, so I'm not sure how this is importable. Looking at it on my own machine, I get:
```
In [1]: import cairocffi

In [2]: cairocffi._generated
Out[2]: <module 'cairocffi._generated' (namespace)>
```
so the `_generated` is not a module.

**Comment by liZe** [comment]
> The `_generated` folder that is built does not have a `__init__.py` generated in it, so I'm not sure how this is importable.

`__init.py__` files are not mandatory since Python 3.3, so it shouldn't be a problem with 3.6. Is your cairocffi module installed with pip?

**Comment by flacjacket** [comment]
It is installed in our tests via pip (see the our [tox.ini](https://github.com/qtile/qtile/blob/master/tox.ini)), but we wind up with problems importing the module. See:
https://travis-ci.org/qtile/qtile/jobs/490956510

**Comment by liZe** [comment]
I've found where the problem comes from. You import `cairocffi.ffi_build` in `libqtile/pango_ffi_build.py` (called by `scripts/ffibuild` in `tox.ini`). Importing this module deletes the generated ffi modules.

You shouldn't import this module that's not part of the public API. But importing this module shouldn't delete the generated modules :smile:. I'll try to find a solution for that.

**Comment by liZe** [comment]
@flacjacket It works now (at least for me).

Note for later: We won't distribute wheels anymore. As we need to compile ffi modules during the installation, it doesn't really make sense.

**Comment by flacjacket** [comment]
Ah, thanks for the fix! We do rely on importing `cairocffi.ffi_build` to be able to build our pangocairo bindings, so I'm glad you could figure it out
