### ISSUE TITLE
ffi not able to load the libcairo.so.2 library

### ISSUE THREAD

**Issue by asdspal** [Kozea/cairocffi#121]
While importing cairocffi, it's giving me error `OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2`. 
I was able to run the following commands successfully:
```
import ctypes.util
ctypes.cdll.LoadLibrary((ctypes.util.find_library( "libcairo.so.2")))
```
It seems the problem is in `lib = ffi.dlopen(path or lib_name)`.   

I'm using kaggle container for which dockerfile is located [here](https://github.com/Kaggle/docker-python/blob/master/Dockerfile).
How do I resolve this error?

**Comment by liZe** [comment]
What does `ctypes.util.find_library('libcairo.so.2')` gives on your system?

**Comment by asdspal** [comment]
I get `/opt/conda/lib/libcairo.so.2`.

**Comment by liZe** [comment]
So… It means that `ffi.dlopen(ctypes.util.find_library('libcairo.so.2'))` doesn't work?

**Comment by asdspal** [comment]
Yes. Any suggestions on what should I do?

**Comment by liZe** [comment]
What's the error you get when calling `ffi.dlopen(ctypes.util.find_library('libcairo.so.2'))`?

**Comment by asdspal** [comment]
Running 
```
from cffi import FFI
ffi = FFI()
ffi.dlopen(ctypes.util.find_library( "libcairo.so.2"))
```
gives me

`<cffi.api._make_ffi_library.<locals>.FFILibrary at 0x7f348c616cc0>`

**Comment by liZe** [comment]
> <cffi.api._make_ffi_library.<locals>.FFILibrary at 0x7f348c616cc0>

Then I don't know what's wrong, and how cairocffi's code can fail. Debugging `dlopen` step by step is a good way to find what's wrong. Could you try this?

**Comment by asdspal** [comment]
I'll try. Also, I tried to install cairocffi using conda package manager. For that, I had to uninstall pytorch-cpu first as it was giving me package conflict error. After installing cairocffi through conda, I was still unable to import the libcairo.so.2 and it gave me the same error.
I'll update on this in 1 or 2 days.

**Comment by asdspal** [comment]
Yesterday, kaggle updates its system and problem resolved on its own. Please close this issue for now.

**Comment by liZe** [comment]
OK!

**Comment by s22chan** [comment]
for conda, it will not load on linux for python2 due to a bad patch (not using startswith for sys.platform) via:

https://github.com/conda-forge/cairocffi-feedstock/blob/master/recipe/dlopen-patch.diff
