### ISSUE TITLE
latest pypi release shows wrong version on `pip freeze`

### ISSUE THREAD

**Issue by tuky** [Kozea/cairocffi#123]
see below for my installation process on ubuntu 18.10. `pip freeze` gives me `cairocffi===file-.cairocffi-VERSION`.

```
tuky@Quiet:/tmp$ python3.6 -m venv /tmp/cairoenv
tuky@Quiet:/tmp$ source /tmp/cairoenv/bin/activate
(cairoenv) tuky@Quiet:/tmp$ pip install -U pip
Cache entry deserialization failed, entry ignored
Collecting pip
  Using cached https://files.pythonhosted.org/packages/d7/41/34dd96bd33958e52cb4da2f1bf0818e396514fd4f4725a79199564cd0c20/pip-19.0.2-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-19.0.2
(cairoenv) tuky@Quiet:/tmp$ pip install -U wheel
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/7c/d7/20bd3c501f53fdb0b7387e75c03bd1fce748a1c3dd342fc53744e28e3de1/wheel-0.33.0-py2.py3-none-any.whl
Installing collected packages: wheel
Successfully installed wheel-0.33.0
(cairoenv) tuky@Quiet:/tmp$ pip install -U cairocffi
Collecting cairocffi
  Using cached https://files.pythonhosted.org/packages/3e/f1/0d1dad825f6ec75d3d79d5673e7b836e7a23bf57fde0028fb8bf252d4259/cairocffi-1.0.1.tar.gz
Collecting cffi>=1.1.0 (from cairocffi)
  Using cached https://files.pythonhosted.org/packages/6d/c0/47db8f624f3e4e2f3f27be03a93379d1ba16a1450a7b1aacfa0366e2c0dd/cffi-1.11.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting pycparser (from cffi>=1.1.0->cairocffi)
Building wheels for collected packages: cairocffi
  Building wheel for cairocffi (setup.py) ... done
  Stored in directory: /home/tuky/.cache/pip/wheels/8d/f0/05/cb8797e3c39d8475b89381d5ac3e3f6d26484ca317abc0c2ce
Successfully built cairocffi
Installing collected packages: pycparser, cffi, cairocffi
Successfully installed cairocffi-file-.cairocffi-VERSION cffi-1.11.5 pycparser-2.19
(cairoenv) tuky@Quiet:/tmp$ pip freeze
cairocffi===file-.cairocffi-VERSION
cffi==1.11.5
pkg-resources==0.0.0
pycparser==2.19
(cairoenv) tuky@Quiet:/tmp$ python --version
Python 3.6.7
(cairoenv) tuky@Quiet:/tmp$ pip --version
pip 19.0.2 from /tmp/cairoenv/lib/python3.6/site-packages/pip (python 3.6)
```

**Comment by jontycg** [comment]
This issue caused Weasyprint to not install for me citing that it needed a version of cairocffi >= 0.9.0. For the time being I fixed the issue by specifying the version for cairocffi to be 1.0.0 in requirements.txt.

**Comment by liZe** [comment]
We now need a more recent of setuptools (you can get rid of this problem by upgrading setuptools before installing). I should update the version needed in the requirements.

**Comment by jasongi-actu** [comment]
this really should have been a major, not a patch release.

**Comment by liZe** [comment]
> this really should have been a major, not a patch release.

1.0.0 **is** a major, isn't it?

**Comment by jasongi-actu** [comment]
1.0.0 works fine, 1.0.1 has the breaking change.

**Comment by liZe** [comment]
> 1.0.0 works fine, 1.0.1 has the breaking change.

Oh, then it's probably because we didn't release a wheel. I have to find a solution about that.

**Comment by liZe** [comment]
Adding the needed version of setuptools to `setup.cfg` seems to fix the problem. I'll release 1.0.2 soon, sorry for the inconvenience.

**Comment by liZe** [comment]
Looks like it's not fixed: https://travis-ci.org/Kozea/WeasyPrint/jobs/493713422

**Comment by liZe** [comment]
> Looks like it's not fixed: https://travis-ci.org/Kozea/WeasyPrint/jobs/493713422

Well, it's a bit more complicated. Installation works, but launching tests doesn't. Launching `python setup.py` doesn't reload setuptools, and thus it fails as tests are launched with the old setuptools (even if the new one is installed). I think that we can live with that.

**Comment by whyscream** [comment]
This still doesn't work for me with 1.0.1 and 1.0.2. The change in the setup script requires the newer setuptools during install but setuptools is also listed (without version in `setup_requires`). Could it be that pinning there solves this issue?

I'm now getting:
```
Collecting cairocffi==1.0.2 (from -r /app/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/0f/0f/7e21b5ddd31b610e46a879c0d21e222dd0fef428c1fc86bbd2bd57fed8a7/cairocffi-1.0.2.tar.gz (68kB)
  Running setup.py (path:/tmp/pip-build-f8d10dda/cairocffi/setup.py) egg_info for package cairocffi produced metadata for project name unknown. Fix your #egg=cairocffi fragments.
Building wheels for collected packages: unknown, unknown
  Running setup.py bdist_wheel for unknown: started
  Running setup.py bdist_wheel for unknown: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/e7/5d/6f/fc3c2364dfd3c4cfd15d786b156077c52209d9af45496fdf12
  Running setup.py bdist_wheel for unknown: started
  Running setup.py bdist_wheel for unknown: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-f8d10dda/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpe1dm50ycpip-wheel- --python-tag cp35:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.5/tokenize.py", line 454, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-f8d10dda/unknown/setup.py'
  
  ----------------------------------------
  Failed building wheel for unknown
  Running setup.py clean for unknown
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-f8d10dda/unknown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.5/tokenize.py", line 454, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-f8d10dda/unknown/setup.py'
  
  ----------------------------------------
  Failed cleaning build dir for unknown
Successfully built unknown
Failed to build unknown
Installing collected packages: unknown
Successfully installed unknown-0.0.0
```
This is on a docker ubuntu 16.04 image, pre-installed setuptools == 20.7.0.

**Comment by liZe** [comment]
> Could it be that pinning there solves this issue?

Can you try to download the current tree, pin the `setup_requires` version and try to install cairocffi with that change?

**Comment by whyscream** [comment]
I just tried, but it doesn't work :(

**Comment by liZe** [comment]
Then I'm afraid setuptools == 20.7.0 is really too old.

**Comment by whyscream** [comment]
Which awesome feature did you start using between 1.0.0 and 1.0.1 that requires  the newer setuptools? 1.0.0. does work.

**Comment by liZe** [comment]
> Which awesome feature did you start using between 1.0.0 and 1.0.1 that requires the newer setuptools? 1.0.0. does work.

The only commit between 1.0.0 and 1.0.1 is 07802d, fixing #120.

**Comment by liZe** [comment]
The real difference is that we don't distribute wheels anymore, as cffi requires a compilation step during installation. Installing from source requires a more recent version of setuptools.

**Comment by whyscream** [comment]
Ah, yes. When I use `pip3 install --no-binary :all:` , install 1.0.0. fails to, but 0.9.0  still works. Looks like the change was here: https://github.com/Kozea/cairocffi/commit/c93eb812ab54ab6666cbeb1c8eb64934c3cc4544 (swichting to `setup.cfg` in stead of `setup.py`)

**Comment by morganwahl** [comment]
In case anyone ends up here like I did, there's some awful pip behavior on display.

If you install `cairocffi` with a version of `setuptools` that's too old, pip will build `cairocffi` with that old setuptools, producing a broken build with this nonsense version number, and then upgrade setuptools because it knows cairocffi doesn't work with the old one. But you'll still have the broken build.

And it's actually even worse: if you uninstall and reinstall cairocffi with the upgrade setuptools, you'll _still_ get the broken build because pip *cached it*. For me doing `rm -rf ~/.cache/pip` fixed that.

**Comment by liZe** [comment]
> If you install `cairocffi` with a version of `setuptools` that's too old, pip will build `cairocffi` with that old setuptools, producing a broken build with this nonsense version number, and then it will upgrade setuptools because it knows cairocffi doesn't work with the old one. But you'll still have the broken build.

1.0.2 is supposed to prevent this, as setuptools >= 39.2.0 is required in setup.cfg. Why didn't pip upgrade setuptools before installing cairocffi?

**Comment by morganwahl** [comment]
@liZe My exact steps were:

```

**Comment by morganwahl** [comment]
I'm not pip expect; does it have a way to specify a _build time_ dependency instead of a _run time_ dependency? Cause it seems like that's exactly what you need.

Also, it needs to not be using cached build with version numbers that aren't at all what you asked for, but that's a separate issue.

**Comment by liZe** [comment]
> As you can see, pip does upgrade setuptools while installing cairocffi, but it makes that broken build of cairocffi _first_. And then proceeds to keep using the cached broken build even though setuptools is upgraded.
> 
> This is very much a pip bug (or bugs), not a cairocffi one. I just thought I'd comment here since this comes up when you search for "file-.cairocffi-VERSION", and it's not easy to debug.

Oh, yes… Pip upgrades setuptools before building cairocffi, but as installing and building is done in the same process (that uses the old version of setuptools), it doesn't work. Pip should reload setuptools before building, but nobody cares because upgrading setuptools before installing a package is a really easy workaround.

Maybe we could open an issue.

**Comment by liZe** [comment]
(By the way, many package managers for Linux distributions upgrade (with deps) and reload themselves before upgrading the other packages.)

**Comment by morganwahl** [comment]
(Oh, I'm well aware. Sometimes I wish the Python community just used portage or some other established tool.)

**Comment by liZe** [comment]
> portage

:heart_eyes:
