### ISSUE TITLE
Pypy friendly _UNSAFE_pycairo_context_to_cairocffi ?

### ISSUE THREAD

**Issue by stuaxo** [Kozea/cairocffi#124]
Hi,
   `_UNSAFE_pycairo_context_to_cairocffi` doesn't work in Pypy, the way it calculates the pointer is unlikely to work in Pypy.

I don't know if there is an alternate way this could be implemented.

**Comment by liZe** [comment]
No idea :disappointed:.

**Comment by stuaxo** [comment]
Fair enough
