### ISSUE TITLE
installation fails on AWS 

### ISSUE THREAD

**Issue by kluz9** [Kozea/cairocffi#125]
Hello, 
I am trying to install cairocffi on AWS linux ami. But it keeps failing with following error:

```
(venv) [root@ip-172-31-21-74 ec2-user]# pip install cairocffi
Collecting cairocffi
Installing collected packages: cairocffi
Exception:
Traceback (most recent call last):
File "/opt/python/run/venv/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 179, in main
status = self.run(options, args)
File "/opt/python/run/venv/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 393, in run
use_user_site=options.use_user_site,
File "/opt/python/run/venv/local/lib/python3.6/dist-packages/pip/_internal/req/init.py", line 57, in install_given_reqs
**kwargs
File "/opt/python/run/venv/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 913, in install
use_user_site=use_user_site, pycompile=pycompile,
File "/opt/python/run/venv/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 445, in move_wheel_files
warn_script_location=warn_script_location,
File "/opt/python/run/venv/local/lib/python3.6/dist-packages/pip/_internal/wheel.py", line 428, in move_wheel_files
assert info_dir, "%s .dist-info directory not found" % req
AssertionError: cairocffi .dist-info directory not found
```

Any idea why .dist-info directory not found ?

**Comment by liZe** [comment]
Looks like the version of pip you're using is the one bundled with your system (and thus an old one) as it's installed in `dist-packages`. You should try to upgrade pip.

**Comment by liZe** [comment]
There's a bug fixed in pip 9.0.1 that looks exactly like this bug: pypa/pip#4120.

**Comment by kluz9** [comment]
I tried to use --no-cache-dir to install. Now it tries to install but for some reason it shows collected packages as unknown. As a result it shows ModuleNotFoundError: No module named 'cairocffi' when i deploy application.

 /opt/python/run/venv/bin/pip3 --no-cache-dir install cairocffi --upgrade
Collecting cairocffi
  Downloading https://files.pythonhosted.org/packages/0f/0f/7e21b5ddd31b610e46a879c0d21e222dd0fef428c1fc86bbd2bd57fed8a7/cairocffi-1.0.2.tar.gz (68kB)
    100% |████████████████████████████████| 71kB 10.1MB/s 
  Generating metadata for package cairocffi produced metadata for project name unknown. Fix your #egg=cairocffi fragments.
Installing collected packages: unknown
  Found existing installation: UNKNOWN 0.0.0
    Uninstalling UNKNOWN-0.0.0:
      Successfully uninstalled UNKNOWN-0.0.0
  Running setup.py install for unknown ... done
Successfully installed unknown-0.0.0

**Comment by kluz9** [comment]
I finally figured it out. If soemone is looking for solution, this is what I did:
First upgrade pip and setuptools on AWS AMI
python -m pip install --upgrade pip
python -m pip install --upgrade setuptools

Then use --no-cache-dir with pip to install cairocffi
python -m pip --no-cache-dir install cairocffi

I created a config file for AWS so pip uses --no-cache-dir every time I deploy. Here is my file:
files:
    "/opt/python/run/venv/pip.conf":
        mode: "000755"
        owner: root
        user: root
        content: |
            [global]
            no-cache-dir=false

This should install cairocffi correctly.

**Comment by liZe** [comment]
> This should install cairocffi correctly.

Thank you!

**Comment by vuonghv** [comment]
This setting `no-cache-dir=false` makes me confused. This is negative of negative.
https://pip.pypa.io/en/stable/user_guide/

**Comment by cjohnson318** [comment]
Thank you @kluz9 for your solution, I'd like to expand on your comment to make it more copy/paste-able. First, I needed to install the `cairo-devel` linux package. I created the config file `01_packages.config` in the `.ebextensions/` directory. (If you're not sure what the `.ebextensions/` directory is, it's a directory that contains configuration that customizes your Elastic Beanstalk deployment. More info here: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/ebextensions.html)

    packages:
      yum:
        git: []
        postgresql93-devel: []
        cairo-devel: []

Next, I created a config file `02_python.config` in the `.ebextensions/` directory per @kluz9 's comment.

    container_commands:
      01_upgrade_pip:
        command: "python -m pip install --upgrade pip"
        leader_only: true
      02_upgradde_setuptools:
        command: "python -m pip install --upgrade setuptools"
        leader_only: true
    
    files:
      "/opt/python/run/venv/pip.conf":
        mode: "000755"
        owner: root
        user: root
        content: |
          [global]
          no-cache-dir=false

**Comment by annshress** [comment]
Thank you @cjohnson318 for nice update. It works like a charm!

**Comment by HenryMehta** [comment]
I don't know it this helps anyone, but I needed to modify the above to install using ElasticBeanstalk.

First, `pip install -r requirements.txt` was run before pip upgrade, so I changed my `02_initial.config` to 

```
container_commands:
  01_upgrade_pip:
    command: "source /opt/python/run/venv/bin/activate && pip install --upgrade pip"
    leader_only: true
  02_upgradde_setuptools:
    command: "source /opt/python/run/venv/bin/activate && pip install --upgrade setuptools"
    leader_only: true
  03_requirements:
    command: "source /opt/python/run/venv/bin/activate && pip install -r requirements.txt"
    leader_only: true



files:
  "/opt/python/run/venv/pip.conf":
    mode: "000755"
    owner: root
    user: root
    content: |
      [global]
      no-cache-dir=false

option_settings:
  "aws:elasticbeanstalk:application:environment":
    DJANGO_SETTINGS_MODULE: "my-app.settings"
    "PYTHONPATH": "/opt/python/current/app/am-app:$PYTHONPATH"
  "aws:elasticbeanstalk:container:python":
    WSGIPath: my-app/my-app/wsgi.py
    NumProcesses: 6
    NumThreads: 20
  "aws:elasticbeanstalk:container:python:staticfiles":
    "/static/": "my-app/static/"
```

I then started getting an error with unable to find `pango`.  So I amended my `01_packages.config` 
```
 packages:
  yum:
    git: []
    ...
    cairo-devel: []
    pango: []
```

**Comment by afrizal423** [comment]
> I finally figured it out. If soemone is looking for solution, this is what I did:
> First upgrade pip and setuptools on AWS AMI
> python -m pip install --upgrade pip
> python -m pip install --upgrade setuptools
> 
> Then use --no-cache-dir with pip to install cairocffi
> python -m pip --no-cache-dir install cairocffi
> 
> I created a config file for AWS so pip uses --no-cache-dir every time I deploy. Here is my file:
> files:
> "/opt/python/run/venv/pip.conf":
> mode: "000755"
> owner: root
> user: root
> content: |
> [global]
> no-cache-dir=false
> 
> This should install cairocffi correctly.

thanks
