### ISSUE TITLE
create_for_rectangle returns  CAIRO_STATUS_INVALID_FORMAT: invalid value for an input cairo_format_t

### ISSUE THREAD

**Issue by stuaxo** [Kozea/cairocffi#13]
I was trying to crop an input image (640x480) by using create_for_rectangle

``` python
        with open(input_image) as f:
            data = f.read()
            source_image, format = pixbuf.decode_to_image_surface( data )

            print source_image.get_width()
            print source_image.get_height()
            bottom_layer = source_image.create_for_rectangle(0, 65, 640, 350)
            #bottom_layer = source_image
```

Output:

640
480
CairoError: cairo returned CAIRO_STATUS_INVALID_FORMAT: invalid value for an input cairo_format_t

**Comment by stuaxo** [comment]
http://cairographics.org/manual/cairo-cairo-surface-t.html#cairo-surface-create-for-rectangle

It looks like this is meant to return a "subsurface", it seems to be listed in this enum:  cairo_surface_type_t as CAIRO_SURFACE_TYPE_SUBSURFACE.

There's a bit of C code in the cairo tests that does something with subsurfaces in here
https://github.com/mrobinson/cairo/blob/master/test/subsurface-image-repeat.c

**Comment by liZe** [comment]
@stuaxo I've tried your original example and it works for me (the surface is created, `get_format()` gives me `1`). Is it solved for you too?

**Comment by stuaxo** [comment]
Apologise for missing this !

Makes sense to close after all this time.
