### ISSUE TITLE
GdkPixbuf bug workaround

### ISSUE THREAD

**Issue by olemoign** [Kozea/cairocffi#133]
GdkPixbuf has a bug where specific files (probably those with integrated thumbnails) can be opened using

```GdkPixbuf.Pixbuf.new_from_file("path_to_image")```

but not 

```
loader = GdkPixbuf.PixbufLoader()
with open("path_to_image", "rb") as f:
    loader.write(f.read())
loader.close()
```

Sadly, CairoCFFI uses the second method, thus I encounter the bug. Would it be possible to have a fallback to the first method if the second fails? 
The bug has been opened 3 years ago and never fixed: https://bugzilla.gnome.org/show_bug.cgi?id=768639

This workaround has been used here: https://github.com/karlch/vimiv/issues/49 / https://github.com/karlch/vimiv/commit/1fbb544b65450fd9dfab7fdc834a3c32d8ddf70b

**Comment by liZe** [comment]
Thank you for this report.

> Sadly, CairoCFFI uses the second method, thus I encounter the bug. Would it be possible to have a fallback to the first method if the second fails?

CairoCFFI provides a function that's called `decode_to_pixbuf`, and whose first argument is `image_data`. It doesn't provide an interface to open files from a filename, and it doesn't provide a complete wrapping of GdkPixbuf.

Moreover, CairoCFFI being just a "Python wrapper" for Cairo (and some of its dependencies), its goal is not to provide workarounds when there's a problem in Cairo, and even more in GdkPixbuf.

So, unfortunately: no, I won't use `gdk_pixbuf_new_from_file` in `decode_to_pixbuf`. It would require to create a dedicated temporary file to store the image, and that's a pretty ugly solution when you provide a function that works with bytes in memory.

The only solution I can think of, if you're interested, is to add `gdk_pixbuf_new_from_file` into the list of supported functions. This way, you'll be able to use `cairocffi.pixbuf.gdk_pixbuf_new_from_file`. Would it be a viable solution for you?

**Comment by olemoign** [comment]
I understand 100% your position, it's not your responsibility to solve a GdkPixbuf bug. I hoped it would be feasible to work around this in CairoCFFI but if it's not, so be it.

As I am actually using WeasyPrint, getting access to ```gdk_pixbuf_new_from_file``` would be a massive task on my side. Not worth it from my perspective.

Thank you for your answer. :)
(I never know when these tickets should be closed, but on my side, it could be.)

**Comment by liZe** [comment]
I hope that GdkPixbuf's bug will be closed soon…
