### ISSUE TITLE
How can I determine the line-height of a font?

### ISSUE THREAD

**Issue by NathanWailes** [Kozea/cairocffi#134]
Hi,

I'm trying to use cairocffi to render text to PNGs which I then stitch into a lyrics video that highlights the currently-performed syllable, kind of like karoake.  You can see an example of the goal here (this example uses PIL instead of cairocffi): https://www.youtube.com/watch?v=9u9ylseLAfU

The problem with PIL is that if I separately-render two parts of a word so that I can have the parts colored differently, the kerning between the letters is lost.

You can see the previous issues I've created here:
- [Pillow - Font spacing changes](https://github.com/python-pillow/Pillow/issues/3977)
- [fontforge - How do I reliably get the kerning information into a file?](https://github.com/fontforge/fontforge/issues/3811)

Anyway, I'm now trying to use cairocffi, but now I'm running into issues because I don't seem to have access to information that PIL provides.  For example, I don't see how I can get the height of the text that is (or will be) rendered to the screen, so that I can use that to properly vertically-position the text or limit the height of the image so that I can overlay it on top of the background image I create with PIL.

Any idea how I could get that information?

**Comment by liZe** [comment]
> Any idea how I could get that information?

Yes!

Cairo provides [text extents](https://www.cairographics.org/manual/cairo-cairo-scaled-font-t.html#cairo-scaled-font-text-extents) with width, height, and other information. You'll find other useful functions on the same page, and on the [text module page](https://www.cairographics.org/manual/cairo-text.html).

If you have more specific questions, you should ask Cairo devs using [their mailing-list or IRC](), they'll probably have more useful answers! CairoCFFI is just a wrapper around Cairo.
