### ISSUE TITLE
Importing cairo raises import error with Python 3.5.7

### ISSUE THREAD

**Issue by sp1ze** [Kozea/cairocffi#137]
`import cairocffi as cairo`
works fine with Python 3.5.6 but fails with Python 3.5.7 with below error:

>>> import cairocffi as cairo
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/usr/local/lib/python3.5/site-packages/cairocffi/__init__.py", line 17, in <module>
     from ._generated.ffi import ffi
 ImportError: No module named 'cairocffi._generated'

Found issue when using weasyprint that imports cairo.

**Comment by liZe** [comment]
Hello!

There's been something wrong with your cairocffi installation. You should try to reinstall it using pip (after upgrading setuptools and pip if possible): `pip install --upgrade --no-cache --force-reinstall cairocffi`.

**Comment by sp1ze** [comment]
That worked, my bad. Thanks!
