### ISSUE TITLE
Add `wheel` to dependencies

### ISSUE THREAD

**Issue by AlexBlandin** [Kozea/cairocffi#140]
This and Weasyprint need [https://pypi.org/project/wheel/](https://pypi.org/project/wheel/) added as a pip requirement along with setuptools, as cairocffi uses `bdist_wheel` in setup, and `wheel` doesn't seem to be included by setuptools by default.

**Comment by AlexBlandin** [comment]
Not sure if this is related to [https://bugs.python.org/issue37481](https://bugs.python.org/issue37481), which depracated `bdist_wininst` in 3.8, specifically on Windows?

**Comment by AlexBlandin** [comment]
So this is primarily a problem on `setuptools`'s end, however including `wheel` as a dependency in the documentation is probably the path of least resistence to avoid `setuptools` related issues given its recent deprecations (including `easy_install`).

**Comment by liZe** [comment]
> So this is primarily a problem on `setuptools`'s end, however including `wheel` as a dependency in the documentation is probably the path of least resistance.

If it works, including it in dependencies would be even better.

**Comment by HenryMehta** [comment]
This is also a problem when trying to load into AWS ElasticBeanstalk.  You get the following error:

```
Collecting cairocffi==1.1.0 (from -r /opt/python/ondeck/app/requirements.txt (line 11))
    Downloading https://files.pythonhosted.org/packages/f7/99/b3a2c6393563ccbe081ffcceb359ec27a6227792c5169604c1bd8128031a/cairocffi-1.1.0.tar.gz (68kB)
    Running setup.py (path:/tmp/pip-build-uprtf2s9/cairocffi/setup.py) egg_info for package cairocffi produced metadata for project name unknown. Fix your #egg=cairocffi fragments.
```

**Comment by liZe** [comment]
Closing #141 would close this issue too, let’s keep one thread of comments in #141.
