### ISSUE TITLE
Support for multiple fonts

### ISSUE THREAD

**Issue by sonalys** [Kozea/cairocffi#146]
Would be great to pass a list of fonts to the lib, and if a glyph doesn't exists on the first font, it get from the second font, like css does.

**Comment by liZe** [comment]
Hi!

CairoCFFI’s goal is to be a Python binding of Cairo, not to add features, so there’s no plan to handle this in the future.

Pango provides [the feature you want](https://developer.gnome.org/pango/stable/pango-Fonts.html#pango-font-description-set-family). You can use it with cairo using pangocairo.
