### ISSUE TITLE
Help, expect color emoji but black and white

### ISSUE THREAD

**Issue by xy-23** [Kozea/cairocffi#148]
I tried the demo:
https://cairocffi.readthedocs.io/en/stable/cffi_api.html#example-using-pango-through-cffi-with-cairocffi
It worked successfully, so I decided to try whether it can generate emoji.
It did generate the emoji, but lost the emoji's color.

My platform is `windows10 x64 python3.7.6 vscode`.

The code:
```
import cairocffi
import cffi

ffi = cffi.FFI()
ffi.cdef('''
    /* GLib */
    typedef void cairo_t;
    typedef void* gpointer;
    void g_object_unref (gpointer object);

    /* Pango and PangoCairo */
    typedef ... PangoLayout;
    typedef enum {
        PANGO_ALIGN_LEFT,
        PANGO_ALIGN_CENTER,
        PANGO_ALIGN_RIGHT
    } PangoAlignment;
    int pango_units_from_double (double d);
    PangoLayout * pango_cairo_create_layout (cairo_t *cr);
    void pango_cairo_show_layout (cairo_t *cr, PangoLayout *layout);
    void pango_layout_set_width (PangoLayout *layout, int width);
    void pango_layout_set_alignment (
        PangoLayout *layout, PangoAlignment alignment);
    void pango_layout_set_markup (
        PangoLayout *layout, const char *text, int length);
''')
gobject = ffi.dlopen('libgobject-2.0-0')
pango = ffi.dlopen('libpango-1.0-0')
pangocairo = ffi.dlopen('libpangocairo-1.0-0')


def gobject_ref(pointer):
    return ffi.gc(pointer, gobject.g_object_unref)


units_from_double = pango.pango_units_from_double


def write_example_pdf(target):
    pt_per_mm = 72 / 25.4
    width, height = 210 * pt_per_mm, 297 * pt_per_mm  # A4 portrait
    surface = cairocffi.PDFSurface(target, width, height)
    context = cairocffi.Context(surface)
    context.translate(0, 300)

    layout = gobject_ref(pangocairo.pango_cairo_create_layout(context._pointer))
    pango.pango_layout_set_width(layout, units_from_double(width))
    pango.pango_layout_set_alignment(layout, pango.PANGO_ALIGN_CENTER)
    markup = '<span>😂</span>'
    markup = ffi.new('char[]', markup.encode('utf8'))
    pango.pango_layout_set_markup(layout, markup, -1)
    pangocairo.pango_cairo_show_layout(context._pointer, layout)


if __name__ == '__main__':
    write_example_pdf(target='pango_example.pdf')

```

And the result:
![image](https://user-images.githubusercontent.com/47266984/75110675-f3ccdc00-566b-11ea-8d14-d5ca818c897a.png)

I have searched the internet about this problem, but didn't find any useful solvtion.

**Comment by liZe** [comment]
Hi!

You probably have to explicitly use a font with color emojis. You can set the `font` attribute of the `<span>` tag, as it’s done in the documentation. You can for example install Google’s [Noto Color Emoji](https://www.google.com/get/noto/) and set `<span font="Noto Color Emoji">`.

Please note that only fonts with bitmap emojis will be handled. Fonts with vector emojis (called SVGinOT, such as [Twitter’s font](https://github.com/eosrei/twemoji-color-font)) are not supported.

**Comment by xy-23** [comment]
It is sad that `Noto Color Emoji` doesn't support `windows`.(Can't be installed🤯)
So I tried `Noto Emoji`(which is B&W), using `<span font="Noto Emoji">`, 
but the result doesn't change, it still used `Segoe UI Emoji`.
 ![image](https://user-images.githubusercontent.com/47266984/75110675-f3ccdc00-566b-11ea-8d14-d5ca818c897a.png)

I'm curious whether color emoji can be generated into pdf/svg on other platforms(`linux` and `MacOS`)

I also tried to use `weasyprint` to download a webpage(this page actually) which has emoji.
the result is very blurry(Seems like a picture and can't be copied)
![image](https://user-images.githubusercontent.com/47266984/75125044-012aaa80-56ee-11ea-9091-8ca47dd98beb.png)

I'm not sure whether this is my problem or the platform problem or cairo or pango's problem, which made me confuesd. I can't find a clear conclusion in the internet.

**Comment by liZe** [comment]
> It is sad that `Noto Color Emoji` doesn't support `windows`.(Can't be installed🤯)

:astonished: 

By the way, Windows probably provides a font with colored emojis by default, you can use it.

> So I tried `Noto Emoji`(which is B&W), using `<span font="Noto Emoji">`,
> but the result doesn't change, it still used `Segoe UI Emoji`.

If Windows provides a font with colored Emojis, you can try it. You can also try other pre-installed font names to check that it works.

> I'm curious whether color emoji can be generated into pdf/svg on other platforms(`linux` and `MacOS`)

It works, at least on Linux. I’m pretty sure that it works on Windows too … once we can tell Pango to use the right font.

> I also tried to use `weasyprint` to download a webpage(this page actually) which has emoji.
> the result is very blurry(Seems like a picture and can't be copied)

Colored emojis actually are bitmaps embedded in fonts, that’s why you’ll get terrible results when you generate PDF files. A solution would be to use vector colored emojis, but Pango (and many other tools, including Chrome) doesn’t support them, and there’s nothing CairoCFFI can do about that :unamused:.

**Comment by xy-23** [comment]
> By the way, Windows probably provides a font with colored emojis by default, you can use it.

The default color emoji in windows is `Segoe UI Emoji`
Here is a screenshot on the font panel of windows:
![image](https://user-images.githubusercontent.com/47266984/75136280-2552af80-571f-11ea-88af-5592e8f9a35a.png)

> If Windows provides a font with colored Emojis, you can try it. You can also try other pre-installed font names to check that it works.

Other font does work... at least when the text in the markup is not emoji.
Like `<span font="Microsoft YaHei Mono">Hello</span>` can works successfully.

But when it comes to emoji, the `<span font="...">` can't get expected result.

I also tried this code to avoid the potential problem in markup:
```
import cairocffi
import cffi

ffi = cffi.FFI()
ffi.cdef('''
    /* GLib */
    typedef void cairo_t;
    typedef void* gpointer;
    void g_object_unref (gpointer object);

    /* Pango and PangoCairo */
    typedef ... PangoLayout;
    typedef ... PangoFontDescription;
    typedef enum {
        PANGO_ALIGN_LEFT,
        PANGO_ALIGN_CENTER,
        PANGO_ALIGN_RIGHT
    } PangoAlignment;

    int pango_units_from_double (double d);
    PangoLayout * pango_cairo_create_layout (cairo_t *cr);
    void pango_cairo_show_layout (cairo_t *cr, PangoLayout *layout);
    void pango_layout_set_width (PangoLayout *layout, int width);
    void pango_layout_set_alignment (
        PangoLayout *layout, PangoAlignment alignment);
    void pango_layout_set_markup (
        PangoLayout *layout, const char *text, int length);

    void pango_layout_set_text (
        PangoLayout *layout, const char *text, int length);

    void pango_layout_set_font_description (
        PangoLayout *layout, const PangoFontDescription *desc);
    
    PangoFontDescription * pango_font_description_new (void);

    void pango_font_description_set_family (
        PangoFontDescription *desc, const char *family);
''')
gobject = ffi.dlopen('libgobject-2.0-0')
pango = ffi.dlopen('libpango-1.0-0')
pangocairo = ffi.dlopen('libpangocairo-1.0-0')


def gobject_ref(pointer):
    return ffi.gc(pointer, gobject.g_object_unref)


units_from_double = pango.pango_units_from_double


def write_example_pdf(target):
    pt_per_mm = 72 / 25.4
    width, height = 210 * pt_per_mm, 297 * pt_per_mm  # A4 portrait
    surface = cairocffi.PDFSurface(target, width, height)
    context = cairocffi.Context(surface)
    context.translate(0, 300)

    layout = gobject_ref(pangocairo.pango_cairo_create_layout(context._pointer))
    pango.pango_layout_set_width(layout, units_from_double(width))
    pango.pango_layout_set_alignment(layout, pango.PANGO_ALIGN_CENTER)

    fontf = 'Noto Emoji'
    fontf = ffi.new('char[]', fontf.encode('utf8'))
    fontdes = pango.pango_font_description_new()
    pango.pango_font_description_set_family(fontdes, fontf)


    markup = '😲'
    markup = ffi.new('char[]', markup.encode('utf8'))
    pango.pango_layout_set_text(layout, markup, -1)
    pango.pango_layout_set_font_description(layout, fontdes)
    
    pangocairo.pango_cairo_show_layout(context._pointer, layout)


if __name__ == '__main__':
    write_example_pdf(target='pango_example.pdf')

```
![image](https://user-images.githubusercontent.com/47266984/75136725-80d16d00-5720-11ea-8089-0c9f9d0574e2.png)
As you can see, I tried to use `Noto Emoji` instead of the default emoji, but the result still frustrating.
I'm sure that I installed `Noto Emoji` properly and I even tested it on Adobe Illustrator, which displayed correctly (btw, I also tested the default emoji font `Segoe UI Emoji`. It also displayed correctly colored emojis on AI)

Could you give me an example which has been proved generating color emoji on windows?

**Comment by liZe** [comment]
> Could you give me an example which has been proved generating color emoji on windows?

I suppose that WeasyPrint works because it forces Pango to use the Freetype backend, and I suppose that Pango’s Win32 backend (used by default on Windows) doesn’t support colored emojis.

If you want to spend some time on this, you can try to use Freetype in your snippet. As far as I can remember, you have to call `pango_context_set_font_map` with a Freetype font map. In WeasyPrint, you’ll find useful code in [`text.py`](https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/text.py#L670) and [`fonts.py`](https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/fonts.py#L266).

**Comment by xy-23** [comment]
Thanks, I will try this later.❤
Considering my ability, I probably need to take a long time until I can finally understand it.😂
B&W emoji isn't so bad, at least it supports svg which is better than a blurry img.
Huge thanks for your help, maybe I can try to test color emoji later on linux.

**Comment by xy-23** [comment]
You are right, after setting `font_map`, it can generate color emoji correctlly.
Thanks!❤
