### ISSUE TITLE
module 'cairocffi' has no attribute 'PDF_METADATA_TITLE'

### ISSUE THREAD

**Issue by grizafisjr** [Kozea/cairocffi#149]
I recently got this issue while I am running Django backend with cairocffi module.

I was trying to create PDF using cairocffi module but I am getting this error.

> module 'cairocffi' has no attribute 'PDF_METADATA_TITLE'

What is the issue?

I am using 

> cairocffi==0.6

**Comment by liZe** [comment]
Hello!

`PDF_METADATA_TITLE` has been added in Cairo 1.16, your version of Cairo is probably older.

**Comment by grizafisjr** [comment]
@liZe 
Thanks for your reply.
I would like to know how to update Cairo 1.16, I don't see cairocffi version 1.16
Cheers,

**Comment by liZe** [comment]
> I would like to know how to update Cairo 1.16, I don't see cairocffi version 1.16

Cairo versions and CairoCFFI versions are different. CairoCFFI is a Python wrapper around Cairo, and each project has its own roadmap with its own releases. CairoCFFI can only provide the features provided by the wrapped version of Cairo.

If you’re on Linux, you’ll probably have to use the version packaged by your distribution. If you really need a more recent version, then upgrade your distribution.

**Comment by liZe** [comment]
Feel free to reopen if needed.
