### ISSUE TITLE
Cannot find existing windows path

### ISSUE THREAD

**Issue by Houdinic** [Kozea/cairocffi#153]
I am using windows 10 and dlopen output that there's no "cairo" or "cairo-2". When using ctypes.util.find_library(), I found it could output the correct path of libcairo-2.dll. After commenting out ffi.dlopen(path) and returning path directly, it works with the returned path.
This is my code change in dlopen function.

    """Try various names for the same library, for different platforms."""
    for name in names:
        for lib_name in [name, 'lib' + name]:
            try:
                path = ctypes.util.find_library(lib_name)
                if path:
                    return path
                    # lib = ffi.dlopen(path)
                    # if lib:
                    #     return lib
            except OSError:
                pass
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))

**Comment by liZe** [comment]
Hello!

The code you’ve modified comes from an old version on cairocffi. Version 1.1.0 probably fixes this problem, you should upgrade cairocffi.

See #119, #135.

**Comment by Houdinic** [comment]
Thank you for updating me on that!
