### ISSUE TITLE
pytest-runner deprecated usage

### ISSUE THREAD

**Issue by edobez** [Kozea/cairocffi#157]
pytest-runner is used in a deprecated way: from _setup_requires_.
Probably most of the times this is not an issue, but in my case when installing this package using pip, the _setup_requires_ step tries to get `pytest-runner` if not already available.
The problem is right here: the way _setup_requires_ tries to get the missing package is not honoring pip configuration, such as different index, certificates, proxies, etc.
This fails the download in my case.

The workaround I found is to install `pytest-runner` first using pip, so it will be found in the _setup_requires_ step.

**Comment by Zhen3r** [comment]
Thanks A LOT! you saved my day
