### ISSUE TITLE
Please add __init__.py to ./_generated folder

### ISSUE THREAD

**Issue by BarchSteel** [Kozea/cairocffi#174]
Hello,
I tried to package a script that uses cairosvg into a stand-alone .exe using py2exe. Py2exe looks for the packages and includes them in a frozen state. However, it has problems when a package does not include an __init__.py.

So, it would be very helpful if the generated folder cairocffi/_generated contained an empty __init__.py

**Comment by liZe** [comment]
It’s been fixed in [py2exe 0.10.2.0](https://github.com/py2exe/py2exe/releases/tag/v0.10.2.0).
