### ISSUE TITLE
AttributeError: module 'constants' has no attribute '_CAIRO_HEADERS'

### ISSUE THREAD

**Issue by SteffenHerbort** [Kozea/cairocffi#176]
Dear developers,

I got the following error when installing drawSvg (cairocffi is a dependency):

```
Collecting drawSvg
  Using cached https://files.pythonhosted.org/packages/b0/25/72b3cc2a84d59b0ccf67c18abe5b896757f22eb31be74a2fe2d6a478f59f/drawSvg-1.7.0-py3-none-any.whl
Collecting cairoSVG (from drawSvg)
  Using cached https://files.pythonhosted.org/packages/ec/8a/1dd6751941e407a4c0ea82a72143d8cfee5d56338bc13c586b1223d8b3ab/CairoSVG-2.5.0-py3-none-any.whl
Collecting imageio (from drawSvg)
  Using cached https://files.pythonhosted.org/packages/6e/57/5d899fae74c1752f52869b613a8210a2480e1a69688e65df6cb26117d45d/imageio-2.9.0-py3-none-any.whl
Requirement already satisfied: numpy in c:\program files (x86)\python36-32\lib\site-packages (from drawSvg)
Collecting cairocffi (from cairoSVG->drawSvg)
  Using cached https://files.pythonhosted.org/packages/84/ca/0bffed5116d21251469df200448667e90acaa5131edea869b44a3fbc73d0/cairocffi-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ANVAR_~1\AppData\Local\Temp\pip-build-1vhwqg6i\cairocffi\setup.py", line 13, in <module>
        'cairocffi/ffi_build.py:ffi_pixbuf']
      File "c:\program files (x86)\python36-32\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\program files (x86)\python36-32\lib\site-packages\setuptools\dist.py", line 318, in __init__
        _Distribution.__init__(self, attrs)
      File "c:\program files (x86)\python36-32\lib\distutils\dist.py", line 281, in __init__
        self.finalize_options()
      File "c:\program files (x86)\python36-32\lib\site-packages\setuptools\dist.py", line 376, in finalize_options
        ep.load()(self, ep.name, value)
      File "c:\program files (x86)\python36-32\lib\site-packages\cffi\setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "c:\program files (x86)\python36-32\lib\site-packages\cffi\setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "c:\program files (x86)\python36-32\lib\site-packages\cffi\setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "cairocffi/ffi_build.py", line 28, in <module>
        ffi.cdef(constants._CAIRO_HEADERS)
    AttributeError: module 'constants' has no attribute '_CAIRO_HEADERS'
```

Can you tell me how to fix it?

**Comment by vors** [comment]
I see the same issue.

**Comment by liZe** [comment]
> I see the same issue.

Do you also have the problem with Python 3.6 32 bits?

If it’s possible for you, I’d like to know if you get the same result with more recent versions of Python, pip and setuptools.

**Comment by liZe** [comment]
The problem also happens on macOS.

It probably comes from the `sys.path.append` hack not working for some reason. It would be interesting to really know why.

**Comment by seterman** [comment]
This just happened to me because there is another package in my PYTHONPATH that also has a `constants.py`, which obviously does not have an attribute `_CAIRO_HEADERS`. I was able to resolve this by installing with `PYTHONPATH='' pipenv install`; the equivalent for whatever installation you're using should hopefully fix it.

**Comment by liZe** [comment]
> This just happened to me because there is another package in my PYTHONPATH that also has a `constants.py`, which obviously does not have an attribute `_CAIRO_HEADERS`.

Oh. Out of curiosity, what’s this package?

**Comment by ade-sculpteo** [comment]
Hi, i'm having the same issue installing via poetry in a project containing Django of which the constants.py file is imported instead of cairocffi's one. Seterman's solution worked for me but i'm not sure i'll be able to do that workaround in production. Is there any chance for a fix ?

**Comment by liZe** [comment]
> Is there any chance for a fix ?

We should import `constants` using [`importlib.util.spec_from_file_location`](https://docs.python.org/3/library/importlib.html?highlight=importlib#importlib.util.spec_from_file_location], instead of using `sys.path.append`. Does anyone have the motivation for a PR? :heart:

**Comment by ade-sculpteo** [comment]
Thanks for your quick reply ! I'll give a shot at PR :)

**Comment by ade-sculpteo** [comment]
Here it is: https://github.com/Kozea/cairocffi/pull/196

I tested it locally and it solves my issue.

**Comment by grewn0uille** [comment]
Fixed by https://github.com/Kozea/cairocffi/pull/196.
