### ISSUE TITLE
Issue on Mac mini M1 (Apple Silicon)

### ISSUE THREAD

**Issue by jdern** [Kozea/cairocffi#181]
I go the following error:
import cairocffi as cairo
  File "/Users/jerome/Library/Python/3.7/lib/python/site-packages/cairocffi/__init__.py", line 50, in <module>
    ('libcairo.so.2', 'libcairo.2.dylib', 'libcairo-2.dll'))
  File "/Users/jerome/Library/Python/3.7/lib/python/site-packages/cairocffi/__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "libcairo-2" was found
cannot load library '/opt/homebrew/Cellar/cairo/1.16.0_5/lib/libcairo.dylib': dlopen(/opt/homebrew/Cellar/cairo/1.16.0_5/lib/libcairo.dylib, 2): no suitable image found.  Did find:
	/opt/homebrew/Cellar/cairo/1.16.0_5/lib/libcairo.dylib: mach-o, but wrong architecture
	/opt/homebrew/Cellar/cairo/1.16.0_5/lib/libcairo.2.dylib: mach-o, but wrong architecture
cannot load library 'libcairo.so.2': dlopen(libcairo.so.2, 2): no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs
cannot load library 'libcairo.2.dylib': dlopen(libcairo.2.dylib, 2): no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs
cannot load library 'libcairo-2.dll': dlopen(libcairo-2.dll, 2): no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs

but checking lib file gives:
lipo -info /opt/homebrew/Cellar/cairo/1.16.0_5/lib/libcairo.dylib                                
Non-fat file: /opt/homebrew/Cellar/cairo/1.16.0_5/lib/libcairo.dylib is architecture: arm64

So what is wrong?
Thanks for any help
Jerome

**Comment by grewn0uille** [comment]
Hello!

It seems that the cairo installed is not compatible with the architecture of your machine.
You can use [homebrew](https://formulae.brew.sh/formula/cairo) to install the library with the correct matching.

**Comment by tiretfa** [comment]
I have the same issue here, and I don't want to change the location of homebrew path.
Any update on that issue ?
