### ISSUE TITLE
Extended unicode support?

### ISSUE THREAD

**Issue by jenstroeger** [Kozea/cairocffi#182]
I’m trying to [`show_text()`](https://cairocffi.readthedocs.io/en/stable/api.html#cairocffi.Context.show_text) a string of UTF8 encoded Arabic or Farsi (both are [rtl scripts](https://en.wikipedia.org/wiki/Right-to-left)) but I get only rectangles. I’ve tried with Apple’s [Monaco](https://en.wikipedia.org/wiki/Monaco_(typeface)) and Google’s [Noto Sans](https://www.google.com/get/noto/#sans-lgc), both of which contain the proper glyphs.

The [Fonts & Text](https://cairocffi.readthedocs.io/en/stable/api.html#fonts-text) section in the manual mentions that

> At the moment cairocffi only supports cairo’s “toy” font selection API.

Does that mean that there’s no support to draw Arabic or Farsi glyphs?

**Comment by liZe** [comment]
Hello! Thanks for this bug report.

I can’t reproduce your problem. Here’s a simple script:
```py
import cairocffi

surface = cairocffi.ImageSurface(cairocffi.FORMAT_ARGB32, 100, 100)
context = cairocffi.Context(surface)
context.move_to(10, 50)
context.select_font_face('DejaVu Sans')
context.show_text('صباح الخير')
context.fill()
surface.write_to_png('/tmp/out.png')
```

It gives me 
![out](https://user-images.githubusercontent.com/952243/112058296-b1215000-8b5a-11eb-87e4-d39ad859e8da.png)

If you only get rectangles, it means that the characters are not in the font you use. You can try to display Roman characters with Monaco or Noto, and check that Cairo uses the right font. The font finding algorithm is not really forgiving, it’s possible that Cairo doesn’t find the right font if the name is not exactly the one it’s waiting for.

**Comment by jenstroeger** [comment]
Thanks @liZe! Good to know that these glyphs _can_ be rendered, then maybe something went awry when I specified/loaded the font. Is there a way of getting some debug information from Cairo into Python regarding the fonts it uses?

**Comment by liZe** [comment]
> Is there a way of getting some debug information from Cairo into Python regarding the fonts it uses?

You can launch WeasyPrint with the `FC_DEBUG` environment variable set to `1` and see how Fontconfig decides which font to use.
