### ISSUE TITLE
On macOS 11, cairocffi raises an OSError

### ISSUE THREAD

**Issue by leeesangwon** [Kozea/cairocffi#191]
On macOS 11, `cairocffi` raises an OSError when using python from conda.

```
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': dlopen(libcairo.so.2, 2): image not found
cannot load library 'libcairo.2.dylib': dlopen(libcairo.2.dylib, 2): image not found
cannot load library 'libcairo-2.dll': dlopen(libcairo-2.dll, 2): image not found
```

I think this is because `ctypes.util.find_library` used [here](https://github.com/Kozea/cairocffi/blob/ec8819316be0de1698deeb976cd8bff638b37eb6/cairocffi/__init__.py#L30) could not find `cairo` on macos11. (https://github.com/python/cpython/pull/21241)
The python included in macOS has a fix for this but not the one from conda I wanna use. :cry:

```
# built-in python
Python 3.9.5 (default, May  3 2021, 19:12:05)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library
>>> find_library('cairo')
'/opt/homebrew/lib/libcairo.dylib'
>>>

# conda python
Python 3.9.5 (default, May 18 2021, 12:31:01)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library
>>> find_library('cairo')
>>>
```
Is there any workaround for this?

**Comment by liZe** [comment]
Hello!

That’s strange, because the Python version you’re using in Conda should include the related PR python/cpython#23295. I think that it’s unrelated.

> >>> find_library('cairo')
> '/opt/homebrew/lib/libcairo.dylib'

The built-in (actually not built-in but installed by Homebrew, isn’t it?) version of Python finds the version of Cairo installed by Homebrew, and this version is not supposed to be used from Conda. Did you also install Cairo with Conda?

**Comment by leeesangwon** [comment]
@liZe 
Yes, as you told me, the Python installed by Conda could not find Cairo installed by Homebrew, but installed by Conda.
After I install Cairo using Conda (`conda install cairo`) everything works perfectly!
Thank you!
