### ISSUE TITLE
1.5.0 is no longer compatible with Msys2 Mingw

### ISSUE THREAD

**Issue by theCapypara** [Kozea/cairocffi#213]
The new release (1.5.0+) can no longer be built on Msys2 MingW envrionemnts under Windows. I thought since it worked before, and this package & the Msys2 environment are basically required to use GTK with Python under Windows, I'd open an issue about it:

```
Collecting cairocffi (from CairoSVG==2.6.0->-r ../requirements-mac-windows.txt (line 15))
  Downloading cairocffi-1.5.1.tar.gz (86 kB)
     ---------------------------------------- 86.9/86.9 kB 1.7 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  error: subprocess-exited-with-error
  
  pip subprocess to install build dependencies did not run successfully.
  exit code: 1
  
  [52 lines of output]
  Collecting setuptools>=61.0.0
    Using cached setuptools-67.7.2-py3-none-any.whl (1.1 MB)
  Collecting cffi>=1.1.0
    Downloading cffi-1.15.1.tar.gz (508 kB)
       -------------------------------------- 508.5/508.5 kB 2.1 MB/s eta 0:00:00
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error
  
    Getting requirements to build wheel did not run successfully.
    exit code: 1
  
    [26 lines of output]
    Traceback (most recent call last):
      File "D:\a\_temp\msys64\mingw64\lib\python3.10\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
        main()
      File "D:\a\_temp\msys64\mingw64\lib\python3.10\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "D:\a\_temp\msys64\mingw64\lib\python3.10\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
        return hook(config_settings)
      File "D:/a/_temp/msys64/tmp/pip-build-env-q3ky0kqd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
        return self._get_build_requires(config_settings, requirements=['wheel'])
      File "D:/a/_temp/msys64/tmp/pip-build-env-q3ky0kqd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
        self.run_setup()
      File "D:/a/_temp/msys64/tmp/pip-build-env-q3ky0kqd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
        super(_BuildMetaLegacyBackend,
      File "D:/a/_temp/msys64/tmp/pip-build-env-q3ky0kqd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
        exec(code, locals())
      File "<string>", line 126, in <module>
      File "<string>", line 105, in uses_msvc
      File "D:/a/_temp/msys64/tmp/pip-build-env-q3ky0kqd/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/config.py", line 223, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "D:/a/_temp/msys64/tmp/pip-build-env-q3ky0kqd/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/config.py", line 128, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "D:/a/_temp/msys64/tmp/pip-build-env-q3ky0kqd/overlay/lib/python3.10/site-packages/setuptools/_distutils/_msvccompiler.py", line 343, in compile
        self.initialize()
      File "D:/a/_temp/msys64/tmp/pip-build-env-q3ky0kqd/overlay/lib/python3.10/site-packages/setuptools/_distutils/_msvccompiler.py", line 246, in initialize
        raise DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: --plat-name must be one of ('win32', 'win-amd64', 'win-arm32', 'win-arm64')
    [end of output]
  
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  Getting requirements to build wheel did not run successfully.
  exit code: 1
  
  See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

pip subprocess to install build dependencies did not run successfully.
exit code: 1

See above for output.
```

Source GitHub Action run for reproducing / reference:
- https://github.com/SkyTemple/skytemple/actions/runs/4837794823/jobs/8621868319

I'm sorry for this brief description, but I sadly don't have much more time to investigate this at the moment. From the looks of it I'm not even sure this is really directly related to cairocffi itself but rather a change in packaging system? Maybe you have more of an idea.

**Comment by liZe** [comment]
Hi!

The problem is in this code in setuptools : https://github.com/pypa/setuptools/blob/e94cb204693cee145ea531905dd50b02a26c9f0a/setuptools/_distutils/_msvccompiler.py#L242-L248

For some reason, `get_platform` returns a value that’s not in `PLAT_TO_VCVARS`.

That’s either a bug in setuptools or in Msys2, but there’s not much we can do about that: the stacktrace literally contains none of our code :/.

> I'm sorry for this brief description, but I sadly don't have much more time to investigate this at the moment. From the looks of it I'm not even sure this is really directly related to cairocffi itself but rather a change in packaging system? Maybe you have more of an idea.

We did change the packaging system, using a `pyproject.toml` file instead of `setup.py`. In both cases we used setuptools, we assumed that it wasn’t such a big change…

**Comment by theCapypara** [comment]
I think the issue is that it even tries an msvc-specific build (`_msvccompiler.py`). That particular code has been there for a while. Something seems to go wrong earlier in the build when it tries to determine the platform...

From what I can see, I think it all starts to go wrong in the `setup.py` of cffi?:
https://foss.heptapod.net/pypy/cffi/-/blob/branch/default/setup.py#L103

That calls `try_compile` to determine if MSVC should be used, which under this new distutils version I guess always tries to use MSVC specific code now to try and compile this statement?

However the code in `config.py` of distutils doesn't really seem to have changed in forever. This is quite the rabbit hole...
At the end I guess it must fail in `get_default_compiler`? https://github.com/pypa/distutils/blame/4435cec31b8eb5712aa8bf993bea3f07051c24d8/distutils/ccompiler.py#L1064
But that uses sys.platform and has an entry for mingw32...

My best guess is that something down the line messes up probably due to some legacy/backwards-compatibility code. 
I'm not really sure where to even report this issue upstream...

**Comment by theCapypara** [comment]
I opened a discussion over at setuptools, let's see if anybody has an idea: https://github.com/pypa/setuptools/discussions/3914

**Comment by theCapypara** [comment]
Yes, however I decided to switch away from Mingw to "normal" Python + gvsbuild for GTK due to a lot of other things that broke with Msys2 due to all the Python packaging changes, so I'm now using this package with MSVC Python on Windows and can't really test this anymore.

**Comment by liZe** [comment]
Then let’s say it’s fixed. If anyone ever hits the same problem, don’t hesitate to reopen.
