### ISSUE TITLE
Documentation links to 32-bit GTK version

### ISSUE THREAD

**Issue by page200** [Kozea/cairocffi#222]
The documentation has [a section titled "Installing cairo on Windows"](https://doc.courtbouillon.org/cairocffi/stable/overview.html#installing-cairo-on-windows), which links to [the 32-bit GTK2 installer](https://gtk-win.sourceforge.io/home/index.php/Main/Downloads). However, that resulted in `cannot load library 'C:\Program Files (x86)\GTK2-Runtime\bin\libcairo-2.dll': error 0xc1` (when doing `from cairosvg import svg2png`, as far as I remember; note that the section is about cairo in general and not only cairocffi). [This discussion of a similar WeasyPrint issue](https://github.com/Kozea/WeasyPrint/issues/957) emphasizes the importance of using a 64-bit version. [The WeasyPrint documentation](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#windows) links to [the 64-bit GTK3 installer](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases), which worked for me.

So maybe the section titled "Installing cairo on Windows" in the cairocffi documentation should additionally link to the 64-bit GTK3 installer and not only the 32-bit GTK2 installer.

**Comment by liZe** [comment]
Hi!

Thanks for opening this issue. Could you please open a pull request to fix this link?

**Comment by mcepl** [comment]
Shouldn’t this be closed?
