### ISSUE TITLE
Missing context.set_hairline()?

### ISSUE THREAD

**Issue by dtromb** [Kozea/cairocffi#226]
It seems like the function `cairo_set_hairline(cairo_boot_t)` (added in 1.18) is missing from the wrapper in context.py.

This function supports drawing wireframe or single pixel scale-independent lines, and is a very important feature to have when debugging graphics renders.

It should be relatively straightforward to add!

**Comment by liZe** [comment]
> It should be relatively straightforward to add!

Yes. Interested in opening a PR?

**Comment by dtromb** [comment]
Ok, will do!  

The comments in the code have annotations as to which version of cairocffi newly added functions were released in, but this isn't targeted to a version.   Just omit?  Or... what version to put there?    (FYI will PR https://github.com/Kozea/cairocffi/issues/81 if you like too since we need that functionality here and will implement regardless)

**Comment by liZe** [comment]
Closed by #227.
