### ISSUE TITLE
cairocffi SVGSurface fail to produce valid svg output

### ISSUE THREAD

**Issue by mnowotka** [Kozea/cairocffi#30]
The code:

    #import cairocffi
    #cairocffi.install_as_pycairo()
    import cairo
    import StringIO

    imageData = StringIO.StringIO()
    surf = cairo.SVGSurface(imageData,200,200)
    ctx = cairo.Context(surf)
    ctx.set_line_width(1)
    ctx.set_source_rgb(0,0,0)
    ctx.move_to(0,0)
    ctx.line_to(100,100)
    surf.finish()
    imageData.getvalue()

If I run it like this (so using original pycairo) I'll get:

    '<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="200pt" height="200pt" viewBox="0 0 200 200" version="1.1">\n<g id="surface1">\n</g>\n</svg>\n'

If I uncomment first two lines (use cairocffi) I'll get:

    '<_cffi_backend.buffer object at 0xa4f22ac><_cffi_backend.buffer object at 0xa4f22ac><_cffi_backend.buffer object at 0xa4f22ac><_cffi_backend.buffer object at 0xa4f22ac><_cffi_backend.buffer object at 0xa4f22ac><_cffi_backend.buffer object at 0xa4f22ac><_cffi_backend.buffer object at 0xa4f22ac><_cffi_backend.buffer object at 0xa4f22ac><_cffi_backend.buffer object at 0xa4f22ac><_cffi_backend.buffer object at 0xa4f22ac>'

**Comment by liZe** [comment]
Now fixed.
