### ISSUE TITLE
Pixbuf error: GIF image was truncated or incomplete.

### ISSUE THREAD

**Issue by SimonSapin** [Kozea/cairocffi#34]
(This bug was initially reported as https://github.com/Kozea/WeasyPrint/issues/179.)

Test image:
![lorem](https://cloud.githubusercontent.com/assets/291359/2626774/c2f14fd8-bde4-11e3-9139-e1ed6ce11d7c.gif)

The image above loads fine in various image viewers. Asking GDK-PixBuf to load it directly from a file also works fine:

```python
import cffi
ffi = cffi.FFI()
ffi.cdef('void* gdk_pixbuf_new_from_file (const char* filename, void** err);')
pixbuf = ffi.dlopen('gdk_pixbuf-2.0')
result = pixbuf.gdk_pixbuf_new_from_file(b'lorem.gif', ffi.NULL)
assert result != ffi.NULL
```

However, using cairocffi’s GDK-PixBuf support fails:

```python
>>> from cairocffi.pixbuf import decode_to_pixbuf
>>> decode_to_pixbuf(open('lorem.gif', 'rb').read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/simon/projects/cairocffi/cairocffi/pixbuf.py", line 155, in decode_to_pixbuf
    handle_g_error(error, gdk_pixbuf.gdk_pixbuf_loader_close(loader, error))
  File "/home/simon/projects/cairocffi/cairocffi/pixbuf.py", line 123, in handle_g_error
    raise ImageLoadingError(message)
cairocffi.pixbuf.ImageLoadingError: Pixbuf error: GIF image was truncated or incomplete.
```

This is either a bug in the way cairocffi uses `GdkPixbufLoader` (although this looks alright based on my reading of [the documentation](https://developer.gnome.org/gdk-pixbuf/stable/GdkPixbufLoader.html#GdkPixbufLoader.description); unfortunately, `gdk_pixbuf_new_from_file` is not based on `GdkPixbufLoader` so we can’t just imitate that), or a bug in the underlying GDK-PixBuf library itself.

`GdkPixbufLoader` seems to be the only way to load an image without first having it on the local filesystem. (For example, downloading it from HTTP as WeasyPrint typically does.)

Many other images (including GIF) do not trigger this problem. The problem disappears after loading this image in GIMP and saving it back again to GIF. It looks like this file is broken/corrupted just enough to trip `cairocffi.pixbuf` or `GdkPixbufLoader`, but still allow other loaders to recover. I don’t know how to debug this further.

**Comment by liZe** [comment]
> The image above loads fine in various image viewers.

It actually looks corrupted. Emacs is not able to read it, GIMP gives a warning (EOF / read error on image data).

The error we get now from `decode_to_pixbuf` is a bit different: `Pixbuf error: Not all frames of the GIF image were loaded.` I think that it's a multi-frame GIF file truncated after the first frame, and that we can safely close this issue.
