### ISSUE TITLE
cairocffi 'module' object has no attribute 'FFI'

### ISSUE THREAD

**Issue by andrecastro0o** [Kozea/cairocffi#62]
Hi, I am trying to use cairocffi in weasyprint. 
I can run it fine as root, but as user when I try to: `python -c "import cairocffi"`

I get: 
<pre>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cairocffi/__init__.py", line 19, in <module>
    from ._ffi import ffi
  File "/usr/local/lib/python2.7/dist-packages/cairocffi/_ffi.py", line 4, in <module>
    ffi = _cffi_backend.FFI('cairocffi._ffi',
AttributeError: 'module' object has no attribute 'FFI'
</pre>

I am using:
cairocffi==0.7
cffi==1.1.2
xcffib==0.3.2

and:
Operating System: Debian GNU/Linux stretch/sid
Kernel: Linux 3.2.0-4-amd64

any clues? thanks

**Comment by SimonSapin** [comment]
@flacjacket, is this something you’ve seen before?

**Comment by flacjacket** [comment]
Odd, I've never seen anything like this. If I didn't know any better, I'd say it was some problem with the cffi install, since it is breaking on the `_cffi_backend.FFI` call, not anything particular to cairocffi.

**Comment by SimonSapin** [comment]
@andrecastro0o You say it works as root. Were you root during install as well? Try this:

```sh
python -c 'print(__import__("_cffi_backend").__file__)'
```

both as root and not. See if it’s the same file name, and if you have read and execute permissions on that files as either user.

**Comment by neumond** [comment]
```
from ._ffi import ffi
```
What does it try to import? I see no _ffi.py file. I have more exceptions there.

```
Python 3.2.5 (b2091e973da69152b3f928bfaabd5d2347e6df46, Nov 09 2014, 00:49:58)
[PyPy 2.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import cairocffi
Traceback (most recent call last):
  File "/home/neumond/natural-selection/.pip/cairocffi/__init__.py", line 19, in <module>
    from ._ffi import ffi
ImportError: No module named cairocffi._ffi

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/neumond/natural-selection/.pip/cairocffi/__init__.py", line 22, in <module>
    from .ffi_build import ffi
  File "/home/neumond/natural-selection/.pip/cairocffi/ffi_build.py", line 26, in <module>
    ffi = FFI()
  File "/home/neumond/natural-selection/.pip/cffi/api.py", line 59, in __init__
    "version mismatch, %s != %s" % (backend.__version__, __version__)
AssertionError: version mismatch, 0.8.6 != 1.1.2
```

**Comment by flacjacket** [comment]
@neumond The `ffi_build.py` file generates `_ffi.py` when it is run with cffi > 1.0. There are fallbacks in place if you haven't generated the file or if you don't have a new enough cffi, however it looks like you have a problem with your cffi install, your cffi backend version is not the same as the cffi version. Are you by chance running with pypy? If not, then you have some deeper problem with your cffi install.

**Comment by neumond** [comment]
@flacjacket I've commented out assert and it magically worked. Cffi's `__version__` for some strange reason is 0.8.6 while package version is 1.1.2.

**Comment by flacjacket** [comment]
Oh, I just noticed it says you're using PyPy right in your prompt. PyPy ships with cffi built in with a version specifically designed for JIT'ing, you should not pip install cffi with pypy. It is finding _cffi_backend out of PyPy, which for PyPy 2.4.0 is cffi 0.8.6, which doesn't match the pip installed version.

**Comment by neumond** [comment]
Thank you for explanation. Didn't know these things. To be honest though, I moved to cairocffi mainly because of moving to PyPy. Here might be much better to output warning instead of assertion fault. Even with 0.8.6 it works pretty good.

**Comment by lsaffre** [comment]
Hi there, I am having this problem under Python 2.7.9, and I have indeed two different cffi_backend files:

    $ python -c 'print(__import__("_cffi_backend").__file__)'
    /home/admin/virtualenvs/a/local/lib/python2.7/site-packages/_cffi_backend.so
    $ sudo -u www-data python -c 'print(__import__("_cffi_backend").__file__)'
    /usr/lib/python2.7/dist-packages/_cffi_backend.x86_64-linux-gnu.so

Excerpt from output of pip freeze:
    cairocffi==0.7.2
    CairoSVG==1.0.22
    cffi==1.7.0

Now I still don't see how to fix this (and how to avoid it in future setups). Please help!

**Comment by lsaffre** [comment]
I discovered a workaround: downgrade to version 0.6:

    pip install -U 'cairocffi<0.7'

Which of course is not a solution...

**Comment by liZe** [comment]
> Hi there, I am having this problem under Python 2.7.9, and I have indeed two different cffi_backend files

@lsaffre It's normal, using `sudo` makes you launch the `python` executable from the system, not from the virtualenv.

**Comment by liZe** [comment]
> I have more exceptions there.

@neumond This should be fixed with 88e94f0.

**Comment by flacjacket** [comment]
I don't really think that is a good solution, what is in place is there to
explicitly not try to install cffi on pypy. You should not install cffi on
pypy because it has its own version built in. There are some old cffi
compatibility things that can be removed if you are willing to drop support
for old pypy versions, and that may help show problems with not having the
cffi module compiled correctly, but you should be careful about having cffi
in the install_requires.

**Comment by liZe** [comment]
> There are some old cffi
> compatibility things that can be removed if you are willing to drop support
> for old pypy versions, and that may help show problems with not having the
> cffi module compiled correctly, but you should be careful about having cffi
> in the install_requires.

@flacjacket Thanks for the warning, I'll check that carefully with the latest versions of pypy!

**Comment by liZe** [comment]
> You should not install cffi on
> pypy because it has its own version built in.

@flacjacket I've tried to use pip to install the current cairocffi repository with PyPy (5.3.1) and PyPy3 (5.2.0-a0). Without the compatibility hacks, it installs a cffi module without any code. It's OK for pip thinking that the package is installed, and it's OK for cairocffi that uses the cffi module from PyPy.

It looks like installing cffi does nothing with PyPy but registering the module as installed for pip. Did I miss anything?

**Comment by flacjacket** [comment]
Hey, sorry for the late response, I guess my main concern is with old versions of PyPy. With newer versions, it is ok since the built in cffi satisfies the requirement, but in older versions it won't and it may try to pip install cffi, which it never should. In my own project, I do something like this: https://github.com/flacjacket/pywayland/blob/master/setup.py#L127
