### ISSUE TITLE
ImportError: No module named 'cairocffi'

### ISSUE THREAD

**Issue by codesdk** [Kozea/cairocffi#77]
I ran pip install cairocffi in my virtual env

==> pip freeze
cairocffi==0.7.2
cffi==1.4.2
pycparser==2.14
wsgiref==0.1.2
(venv)

I am running the tenprintcover.py script 

https://github.com/mgiraldo/tenprintcover-py

with the following arguments

==> python3 tenprintcover.py --author "Clive Barker" --title "Imagica" --cover barker-imagica.png

I am getting the following error 
==> python3 tenprintcover.py --author "Arunabh Das" --title "Sails JS" --cover sailsjs.png
Traceback (most recent call last):
  File "tenprintcover.py", line 23, in <module>
    import cairocffi as cairo
ImportError: No module named 'cairocffi'
(venv)

**Comment by stuaxo** [comment]
Are both pip and python3 running from the virtualenv ?

Run ```which python3``` and ```which pip``` - the output should both be from the venv.

**Comment by liZe** [comment]
@codesdk Is this issue fixed now?
