### ISSUE TITLE
Cannot find gdk-pixbuf-2.0 on AmzonLinux

### ISSUE THREAD

**Issue by daMogli** [Kozea/cairocffi#83]
I believe I have gdk-pixbuf installed however it cannot be opened.

`>>> from cairocffi import pixbuf`
`Traceback (most recent call last):`
  `File "<stdin>", line 1, in <module>`
  `File "/usr/local/lib/python2.7/site-packages/cairocffi/pixbuf.py", line 29, in <module>`
   ` gdk_pixbuf = dlopen(ffi, 'gdk_pixbuf-2.0', 'gdk_pixbuf-2.0-0')`
 ` File "/usr/local/lib/python2.7/site-packages/cairocffi/__init__.py", line 49, in dlopen`
   ` raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))`
`OSError: dlopen() failed to load a library: gdk_pixbuf-2.0 / gdk_pixbuf-2.0-0`

running: `locate libgdk_pixbuf-2.0`
you can see where it is installed:
`/usr/local/lib/libgdk_pixbuf-2.0.so`
`/usr/local/lib/libgdk_pixbuf-2.0.so.0`
`/usr/local/lib/libgdk_pixbuf-2.0.so.0.2107.0`

**Comment by SimonSapin** [comment]
(I’ve reformatted your comment to use ```` ``` ```` code blocks.)

This is *probably* not a bug in cairocffi. Still: 

Does it help to run your program with a `LD_LIBRARY_PATH=/usr/local/lib` environment variable?

Does this work? `import cffi; cffi.FFI().dlopen('/usr/local/lib/libgdk_pixbuf-2.0.so')`

**Comment by daMogli** [comment]
Yes. That allowed the import to work. However when I try to run a program called WeasyPrint that uses this library i get the following error: 

```
  File "/usr/local/lib/python2.7/site-packages/cairocffi/pixbuf.py", line 125, in decode_to_image_surface
    else pixbuf_to_cairo_slices(pixbuf) if not pixbuf.get_has_alpha()
  File "/usr/local/lib/python2.7/site-packages/cairocffi/pixbuf.py", line 155, in pixbuf_to_cairo_slices
    pixels = ffi.buffer(pixbuf.get_pixels(), pixbuf.get_byte_length())
  File "/usr/local/lib/python2.7/site-packages/cairocffi/pixbuf.py", line 73, in __getattr__
    function = getattr(gdk_pixbuf, 'gdk_pixbuf_' + name)
ffi.error: symbol 'gdk_pixbuf_get_byte_length' not found in library 'libgdk_pixbuf-2.0.so.0': /usr/local/lib/libgdk_pixbuf-2.0.so.0: undefined symbol: gdk_pixbuf_get_byte_length
```

**Comment by SimonSapin** [comment]
https://developer.gnome.org/gdk-pixbuf/unstable/gdk-pixbuf-The-GdkPixbuf-Structure.html#gdk-pixbuf-get-byte-length says "Since: 2.26", which version do you have?

**Comment by daMogli** [comment]
I had 2.23. Upgraded to 2.26 and it works now. Thanks for your help!
