### ISSUE TITLE
test_scaled_font failed

### ISSUE THREAD

**Issue by avnik** [Kozea/cairocffi#88]
_______________________________ test_scaled_font _______________________________

```
def test_scaled_font():
    font = ScaledFont(ToyFontFace())
    font_extents = font.extents()
    ascent, descent, height, max_x_advance, max_y_advance = font_extents
#    assert height > ascent + descent  # Not even this is true on all fonts
    assert max_x_advance > 0
    assert max_y_advance == 0
    _, _, _, _, x_advance, y_advance = font.text_extents('i' * 10)
    assert x_advance > 0
    assert y_advance == 0

    font = ScaledFont(ToyFontFace('monospace'))
    _, _, _, _, x_advance_mono, y_advance = font.text_extents('i' * 10)
```

> ```
>   assert x_advance_mono > x_advance
> ```
> 
> E       assert 60.00000000000001 > 60.00000000000001

/nix/store/d2gqbys7fn3nnjvsnmpcmjzcqppz2gpm-python2.7-cairocffi-0.7.2/lib/python2.7/site-packages/cairocffi/test_cairo.py:1001:

Also FONTCONFIG_FILE variable exported, pointing on valid config with single font package inside:  freefont_ttf

Whole package expression, which fail to build - just if you curious https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/python-packages.nix#L3089

**Comment by liZe** [comment]
@avnik You're probably launching the tests on a system where the default font is the default monospace font, even with `FONTCONFIG_FILE` set. Can you try to launch `fc-match` and `fc-match monospace` with `FONTCONFIG_FILE`, set check that you don't get the same font?
