### ISSUE TITLE
No module named _ffi

### ISSUE THREAD

**Issue by retsyo** [Kozea/cairocffi#94]
so did I misunderstand something?

>>> import cairocffi as cairo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\prg\py\pure_pylib\_IO\_image\_cairocffi\cairocffi\__init__.py", line
18, in <module>
    from ._ffi import ffi
ImportError: No module named 'cairocffi._ffi'

**Comment by retsyo** [comment]
it seems a simple _ffi.py solves the problem:
`from cffi import FFI`
`ffi = FFI()`

**Comment by liZe** [comment]
Is that somehow related to #62?

**Comment by liZe** [comment]
Feel free to reopen if needed.
