### ISSUE TITLE
write_to_png does not save color shades

### ISSUE THREAD

**Issue by matthiasmiller** [Kozea/cairocffi#97]
I'm trying to create a PNG using cairocffi, but it's not rendering shades of colors. They get rendered as 0 or 255, depending on the specific shade.

    import cairocffi
    
    surface = cairocffi.ImageSurface(cairocffi.FORMAT_ARGB32, 400, 400)
    context = cairocffi.Context(surface)
    with context:
        # Transparent background
        context.rectangle(0, 0, image_width, image_height)
        context.set_source_rgba(0,0,0,0)
        context.fill()

        # Gray border
        context.set_line_width(1)
        context.set_source_rgb(128,128,128)
        context.rectangle(100, 100, 100, 100)
        context.stroke()

    surface.write_to_png('test.png')

This happens on Windows, but I'm encountering the same issue on my Ubuntu install. I'm using cairocffi because I need to run it in a virtual environment.

I ended up writing this function, which successfully saved it to a PNG with the right colors. Seems to be a bug with write_to_png:

    def cairo_to_png(surface):
        assert sys.byteorder == 'little'
        assert surface.get_format() == cairocffi.FORMAT_ARGB32

        surface.flush()
        argb_image_data = str(surface.get_data())

        # Hard-coded conversion for ARGB32 to RGBA
        rgba_image_data = cStringIO.StringIO()
        for i in range(0, len(argb_image_data), 4):
            rgba_image_data.write(argb_image_data[i+2])
            rgba_image_data.write(argb_image_data[i+1])
            rgba_image_data.write(argb_image_data[i+0])
            rgba_image_data.write(argb_image_data[i+3])

        img = PIL.Image.fromstring('RGBA', (surface.get_width(), surface.get_height()),
                                   rgba_image_data.getvalue())

        png = cStringIO.StringIO()
        img.save(png, "PNG", optimize=True)
        return png.getvalue()

Also, I ran into the same issue when the background was pure white, instead of transparent.

**Comment by liZe** [comment]
After one long year…

It's not a bug in CairoCFFI, it's just how Cairo works. Directly using the C library gives the same result. You can send a message on their mailing list, but I'm pretty sure that it's not a bug for them: a transparent pixel is a transparent pixel at the end, and there are probably many optimizations in internal Cairo functions thanks to this behavior.
